name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        env:
          GOOS: linux
          CGO_ENABLED: 0
          GOARCH: ${{ matrix.arch }}
        run: |
          cd cmd && go build -trimpath -ldflags "-s -w -X main.Version=${GITHUB_REF#refs/tags/} -H=windowsgui -buildid=" -o ../unbind-installer-${{ matrix.arch }} && cd ..
          gzip -9 -k unbind-installer-${{ matrix.arch }}
          sha256sum unbind-installer-${{ matrix.arch }}.gz > unbind-installer-${{ matrix.arch }}.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            unbind-installer-amd64.gz
            unbind-installer-amd64.gz.sha256
            unbind-installer-arm64.gz
            unbind-installer-arm64.gz.sha256
          body: |
            ## Unbind Installer Release

            This release includes binaries for:
            - Linux AMD64
            - Linux ARM64

            ### Installation

            ```bash
            curl -fsSL https://raw.githubusercontent.com/unbindapp/unbind-installer/main/install.sh | sudo bash
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        arch: [amd64, arm64]
